mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
      -DCMAKE_FIND_ROOT_PATH="%LIBRARY_PREFIX%" ^
      -DBUILD_SHARED_LIBS=ON ^
      -DCMAKE_BUILD_TYPE=Release ^
      -DOPENEXR_BUILD_TOOLS=OFF ^
      -DOPENEXR_BUILD_EXAMPLES=OFF ^
      -DBUILD_TESTING=OFF ^
      -G "Ninja" ..

ninja install