context:
  name: ilmbase
  version: "3.4.6"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/AcademySoftwareFoundation/openexr/archive/v${{ version }}.tar.gz
  sha256: f8cfe743a81c8cc1dd3cbaafa7fa76f75ad31456b0fc45a42b086d12530a4e35

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  run_exports:
    # https://abi-laboratory.pro/\?view\=timeline\&l\=ilmbase
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - OpenEXR/half.h
        - OpenEXR/IlmThread.h
        - OpenEXR/ImathMath.h
        - OpenEXR/Iex.h
        - OpenEXR/IexMathExc.h
      lib:
        - Half
        - IlmThread
        - Imath
        - Iex
        - IexMath

about:
  homepage: http://www.openexr.com/
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: IlmBase libraries required for OpenEXR.
  documentation: http://www.openexr.com/documentation.html

extra:
  recipe-maintainers:
    - npavlovikj
    - SylvainCorlay
    - wolfv
    - JohanMabille
